### ISSUE TITLE
Ломает SSR

### ISSUE THREAD

**Issue by eolme** [VKCOM/vkjs#16]
Например, в `InputUtils.ts` используются глобальные переменный без проверки `canUseDOM`

**Comment by ewgenius** [comment]
Fix #24

**Comment by eolme** [comment]
Пометить бы как-нибудь функции недоступные на стороне сервера, либо заглушки сделать

**Comment by ewgenius** [comment]
Исправлено в #24, релиз 0.20.0

> Пометить бы как-нибудь функции недоступные на стороне сервера, либо заглушки сделать
Сейчас все функции должны отрабатывать при SSR без ошибок
